# config.yaml
device: "cuda"  # or "cpu"
experiment:
  train: False
  validate: True
  run_id: 3
  plot_save_path: 2d_plot
  start_from_checkpoint: False
  checkpoint_path: 'runs/0/model_checkpoint_548.pth'  
  save_ckpt_every_n_epochs: 10
  val_every_n_epochs: 10


training:
  batch_size: 32
  epochs: 300
  finetune_epochs: 300
  initial_epochs: 10000
  learning_rate: 0.00001
  initial_learning_rate: 0.0001

sequence_length: [3, 2]
sim_fields: ["dens", "pres"]
sim_params: ["mach"]
diffusion_steps: 20

data:
  mode: "Training"
  data_dirs: ["/home/autoreg-pde-diffusion/data"]
  filter_top: ["128_small_tra"]
  filter_sim: [[0]]
  excludefilter_sim: False
  filter_frame: [(250, 1000)]
  rand_seq_offset: True
  print_level: "sim"
  normalize_mode: "traMixed"

dataloader:
  num_workers: 2

model:
  diffusion_steps: 20
  input_steps: 2
