# config.yaml
device: "cuda"  # or "cpu"
experiment:
  train: True
  validate: True
  analysis: True
  run_id: 13
  project: kol
  plot_file_name: 2d_plot
  plot_video: True
  stability_file_name: temporal_stability
  spectral_analysis: spec_analysis
  save_plot_video_path: pred_video
  eval_node: eval_node
  start_from_checkpoint: False
  checkpoint_path: 'runs/kol/12/model_checkpoint_30.pth'  
  # checkpoint_path: 'runs/kol/3/model_checkpoint_88.pth'  
  save_ckpt_every_n_epochs: 3
  val_every_n_epochs: 200


data:
  mode: "Training"
  data_dirs: "/home/autoreg-pde-diffusion/data/kol/results_2.h5"
  total_seq_len: 10
  rollout_total_seq_len: 600
  val_downsample_k: 2  # val_downsample_k * rollout_total_seq_len <= total_len * val_ratio
  train_ratio: 0.8
  val_ratio: 0.15
  crop: 0


model:
  diffusion_steps: 20
  input_steps: 9
  output_steps: 1
  total_steps: 10
  data_channels: 2


training:
  batch_size: 16
  finetune_epochs: 40
  finetune_learning_rate: 0.00001  
  epochs: 100
  learning_rate: 0.0001

validation:
  n_val_samples: 1

dataloader:
  num_workers: 2


